### PR TITLE
Database-Performance

### PR DESCRIPTION
**Pull request by nunegabriel**
In the following pull request we did the following:

- [ ] Optimized the performance of SELECT COUNT(*) FROM visits where animal_id = 4;

BEFORE:
Screenshot (81)

AFTER:
Screenshot (77)

- [ ] Optimized the performance of SELECT * FROM visits where vet_id = 2;
BEFORE:
Screenshot (84)
AFTER:

Capture

- [ ] Optimized the performance of SELECT * FROM owners where email = 'owner_18327@mail.com';
BEFORE:
Capture-1
AFTER:

Capture-2

### CODE REVIEW

**Review by rotimiazeez — CHANGES_REQUESTED** [review]
# Hi Team 👍🏽,
# Your are almost there 💯 
## Good job so far! 
### To Highlight 👇🏽
- No Linter error ✔️ 
- Good PR description 👍🏽 
- Good commit message(s) 😉
You still need to work on some issues to prepare your project for the final evaluation, but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR WORDS>


## Suggested changes
- Kindly add screenshots for the 
* `SELECT * FROM visits where vet_id = 2;`
* `SELECT * FROM owners where email = 'owner_18327@mail.com';` query to prove that the execution time AFTER the improvements is lower than BEFORE the improvements.


Please feel free to use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you consider them as they can improve your code._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag (@rotimiazeez) me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by nunegabriel** [comment]
@rotimiazeez  The changes are in the same screenshot I did not separate them.

**Comment by rotimiazeez** [comment]
@nunegabriel,
I see query plan, but you did not implement it as you did the first screenshot. Kind make you have the Before and After as you did for the first screenshot, and please try to be consistent with PR like this.
Best

**Review by elisha2kyakpo1 — APPROVED** [review]
Hi 👋 team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

👍 You did well to add the screenshots as requested by the previous reviewer.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by demix007** [comment]
## Hello @elisha2kyakpo1 :wave,

Thank you for taking out time to review and approve this PR. 💯

**Pull request merged**
